In [151]:
import numpy as np
import pandas as pd

In [152]:
df=pd.read_csv('bayes.csv')
df

     Outlook Temparature Humidity   Windy Class
0      sunny         hot     high    weak     N
1      sunny         hot     high  strong     N
2   overcast         hot     high    weak     P
3       rain        mild     high    weak     P
4       rain        cool   normal    weak     P
5       rain        cool   normal  strong     N
6   overcast        cool   normal  strong     P
7      sunny        mild     high    weak     N
8      sunny        cool   normal    weak     P
9       rain        mild   normal    weak     P
10     sunny        mild   normal  strong     P
11  overcast        mild     high  strong     P
12  overcast         hot   normal    weak     P
13      rain        mild     high  strong     N

In [153]:
n=0
y=0
t=len(df)
for x in df['Class']:
    if x=='N':
        n=n+1
    else:
        y=y+1

In [154]:
#TRAINING 
def calculateProb(x,it):
    no=yes=0
    array=np.array(df[x])
    index=np.where(array==it)[0]
    for i in index:
        if df['Class'][i]=='N':
            no=no+1
        else:
            yes=yes+1
    return yes/y,no/n

In [155]:
prob_yes=y/t
prob_no=n/t
ls_yes=[]
ls_no=[]
#TESTING
for i in range(len(df.columns)-1):
    value=df.columns[i]
    print(value)
    it=input("enter value: ")
    kyes,kno=calculateProb(value,it)
    ls_yes.append(kyes)
    ls_no.append(kno)
for x in ls_yes:
    prob_yes=prob_yes*x
for x in ls_no:
    prob_no=prob_no*x
# print(prob_yes)
# print(prob_no)
if(prob_yes>prob_no):
    print("Play Tennis=YES")
else:
    print("Play Tennis=NO")

Outlook
enter value: sunny
Temparature
enter value: cool
Humidity
enter value: high
Windy
enter value: strong
Play Tennis=NO